### PR TITLE
v0.0.6

### PR DESCRIPTION
**Pull request by MyDragonBreath**

### CODE REVIEW

**Comment by AmongUsDev** [comment]
When this pull request get merged ?

**Comment by MyDragonBreath** [comment]
It'll get merged tomorrow once I'm sure there's nothing wrong with any of the code- didn't have much time to test today. Until then you can download the build artefact if you wish to use it now.

**Comment by AmongUsDev** [comment]
i use it but there an issue : when you go and create an lobby in Local and you add 5-6 player and you choose submerged an message cannot start as following player have not submerged : BOT 1 BOT2 BOT 3

**Comment by AmongUsDev** [comment]
my idea : is when MCI installed disable the cannot start .. feature for submerged

**Comment by MyDragonBreath** [comment]
Please check if you have the beta 2 install of submerged properly installed- as in this build it should allow you to start anyway. You will be able to tell if everything is working correctly as MCI will display a [Submerged] tag in the top right hand corner

**Comment by whichtwix** [comment]
i cant start either with a fresh install, and the mod is saying the submergedcompatibility.loaded bool is false while in lobby

**Comment by AmongUsDev** [comment]
i have the beta 2 of submerged but when i choose submerged map and i add players an message cannot start at following playing dosent have submerged installed

**Comment by AmongUsDev** [comment]
I think you Must add in MCIPlugin.cs `[BepInDependency(SubmergedCompatibility.SUBMERGED_GUID.BepInDependency.DependencyFlags.SoftDependency)]`

**Comment by whichtwix** [comment]
as in i did a console.writeline to check it

**Comment by AmongUsDev** [comment]
you update readme now

**Comment by AmongUsDev** [comment]
I will test to see if the issue fixed

**Comment by AmongUsDev** [comment]
it work now perfect

**Comment by MyDragonBreath** [comment]
cleared for release

**Pull request merged**
